export const CACHE_MAX_AGE_MINUTES = 5;
export const CACHE_MAX_ENTRIES = 100;
export const CACHE_CLEANUP_BUFFER = 10;

const SECONDS_PER_MINUTE = 60;
const MILLISECONDS_PER_SECOND = 1000;
export const MILLISECONDS_PER_MINUTE = SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;
